In [1]:
import numpy as np

$ \phi_j(X) = \exp^{-(\frac{(X-\mu_j)^2}{\sigma^2})}$
* $\mu_j$ controls the position along x-axis and varies from (-1,1). 
* $\sigma$ controls width/spacing

In [4]:
X = np.array( [[1.4 , 1.9],[4.5,5.3]] )
print(X)
print(X.shape)

[[1.4 1.9]
 [4.5 5.3]]
(2, 2)


In [3]:
mu=np.linspace(-1,1,5).reshape(1,-1)
print(mu)
print(mu.shape)

[[-1.  -0.5  0.   0.5  1. ]]
(1, 5)


In [5]:
a = X.repeat(mu.shape[1],axis=1) 
a

array([[1.4, 1.4, 1.4, 1.4, 1.4, 1.9, 1.9, 1.9, 1.9, 1.9],
       [4.5, 4.5, 4.5, 4.5, 4.5, 5.3, 5.3, 5.3, 5.3, 5.3]])

In [6]:
b = np.tile(mu,X.shape[1])
b

array([[-1. , -0.5,  0. ,  0.5,  1. , -1. , -0.5,  0. ,  0.5,  1. ]])

In [14]:
np.exp((-1)*( ((a-b)**2)/(sigma**2) ))

array([[7.02066780e-251, 1.65841048e-157, 7.55581902e-086,
        6.63967720e-036, 1.12535175e-007, 0.00000000e+000,
        7.02066780e-251, 1.65841048e-157, 7.55581902e-086,
        6.63967720e-036],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [16]:
def gaussian_basis (X,mu,sigma):
    a = X.repeat(mu.shape[1],axis=1) 
    b = np.tile(mu,X.shape[1])
    phi  = np.exp ( (-1)*( (a-b)**2/(sigma**2) ) )
    return phi

In [9]:
sigma = 0.1
gaussian_basis (X,mu,sigma)

array([[7.02066780e-251, 1.65841048e-157, 7.55581902e-086,
        6.63967720e-036, 1.12535175e-007, 0.00000000e+000,
        7.02066780e-251, 1.65841048e-157, 7.55581902e-086,
        6.63967720e-036],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])